steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - >-
    us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/my-image:$COMMIT_SHA
  - '-f= [Dockerfile path]
  - .
  id: Build image
  timeout: 600s
